# Generated by Django 4.2.11 on 2024-04-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
