# Generated by Django 5.0.4 on 2024-04-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiara', '0002_personne_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='age_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='nom_modifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='prenom_modifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
